name: Run Hello-world from py Script
on: push

jobs:
    Hello:
        runs-on: ubuntu-latest


        steps:
            - name: Clone repo
              uses: actions/checkout@v4
              
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10' 
            
            - name: Run a py script
              run: python hello.py
          













- uses: actions/checkout@v4
